services:
  iris-apis:
    image: ghcr.io/rayer/irisapis:latest
    container_name: iris-apis
    restart: always
    ports:
      - "127.0.0.1:8800:8800"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
