services:
  iris-apis:
    build: .
    container_name: iris-apis
    restart: always
    ports:
      - "127.0.0.1:8800:8800"
    volumes:
      - ./config.yaml:/app/config.yaml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_DOMAIN=grafana.rayer.idv.tw
      - GF_SERVER_ROOT_URL=https://grafana.rayer.idv.tw/
      - GF_SECURITY_ADMIN_USER=rayer
      - GF_SECURITY_ADMIN_PASSWORD=irisgrafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
