// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: ArticleProcessorService.proto

package IrisAPIsGRPC

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProcessTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text         string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	BytesPerLine int64  `protobuf:"varint,2,opt,name=BytesPerLine,proto3" json:"BytesPerLine,omitempty"`
}

func (x *ProcessTextRequest) Reset() {
	*x = ProcessTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArticleProcessorService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextRequest) ProtoMessage() {}

func (x *ProcessTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ArticleProcessorService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextRequest.ProtoReflect.Descriptor instead.
func (*ProcessTextRequest) Descriptor() ([]byte, []int) {
	return file_ArticleProcessorService_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ProcessTextRequest) GetBytesPerLine() int64 {
	if x != nil {
		return x.BytesPerLine
	}
	return 0
}

type ProcessTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessedText string `protobuf:"bytes,1,opt,name=processedText,proto3" json:"processedText,omitempty"`
}

func (x *ProcessTextResponse) Reset() {
	*x = ProcessTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ArticleProcessorService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextResponse) ProtoMessage() {}

func (x *ProcessTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ArticleProcessorService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextResponse.ProtoReflect.Descriptor instead.
func (*ProcessTextResponse) Descriptor() ([]byte, []int) {
	return file_ArticleProcessorService_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessTextResponse) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

var File_ArticleProcessorService_proto protoreflect.FileDescriptor

var file_ArticleProcessorService_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x49, 0x72, 0x69, 0x73, 0x41, 0x50, 0x49, 0x73, 0x47, 0x52, 0x50, 0x43, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a,
	0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x50, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x50, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x32, 0x6f, 0x0a, 0x17, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x20, 0x2e, 0x49, 0x72, 0x69, 0x73, 0x41, 0x50, 0x49, 0x73, 0x47, 0x52, 0x50,
	0x43, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x49, 0x72, 0x69, 0x73, 0x41, 0x50, 0x49, 0x73, 0x47,
	0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ArticleProcessorService_proto_rawDescOnce sync.Once
	file_ArticleProcessorService_proto_rawDescData = file_ArticleProcessorService_proto_rawDesc
)

func file_ArticleProcessorService_proto_rawDescGZIP() []byte {
	file_ArticleProcessorService_proto_rawDescOnce.Do(func() {
		file_ArticleProcessorService_proto_rawDescData = protoimpl.X.CompressGZIP(file_ArticleProcessorService_proto_rawDescData)
	})
	return file_ArticleProcessorService_proto_rawDescData
}

var file_ArticleProcessorService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ArticleProcessorService_proto_goTypes = []interface{}{
	(*ProcessTextRequest)(nil),  // 0: IrisAPIsGRPC.ProcessTextRequest
	(*ProcessTextResponse)(nil), // 1: IrisAPIsGRPC.ProcessTextResponse
}
var file_ArticleProcessorService_proto_depIdxs = []int32{
	0, // 0: IrisAPIsGRPC.ArticleProcessorService.ProcessText:input_type -> IrisAPIsGRPC.ProcessTextRequest
	1, // 1: IrisAPIsGRPC.ArticleProcessorService.ProcessText:output_type -> IrisAPIsGRPC.ProcessTextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ArticleProcessorService_proto_init() }
func file_ArticleProcessorService_proto_init() {
	if File_ArticleProcessorService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ArticleProcessorService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ArticleProcessorService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ArticleProcessorService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ArticleProcessorService_proto_goTypes,
		DependencyIndexes: file_ArticleProcessorService_proto_depIdxs,
		MessageInfos:      file_ArticleProcessorService_proto_msgTypes,
	}.Build()
	File_ArticleProcessorService_proto = out.File
	file_ArticleProcessorService_proto_rawDesc = nil
	file_ArticleProcessorService_proto_goTypes = nil
	file_ArticleProcessorService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleProcessorServiceClient is the client API for ArticleProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleProcessorServiceClient interface {
	ProcessText(ctx context.Context, in *ProcessTextRequest, opts ...grpc.CallOption) (*ProcessTextResponse, error)
}

type articleProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleProcessorServiceClient(cc grpc.ClientConnInterface) ArticleProcessorServiceClient {
	return &articleProcessorServiceClient{cc}
}

func (c *articleProcessorServiceClient) ProcessText(ctx context.Context, in *ProcessTextRequest, opts ...grpc.CallOption) (*ProcessTextResponse, error) {
	out := new(ProcessTextResponse)
	err := c.cc.Invoke(ctx, "/IrisAPIsGRPC.ArticleProcessorService/ProcessText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleProcessorServiceServer is the server API for ArticleProcessorService service.
type ArticleProcessorServiceServer interface {
	ProcessText(context.Context, *ProcessTextRequest) (*ProcessTextResponse, error)
}

// UnimplementedArticleProcessorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedArticleProcessorServiceServer struct {
}

func (*UnimplementedArticleProcessorServiceServer) ProcessText(context.Context, *ProcessTextRequest) (*ProcessTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessText not implemented")
}

func RegisterArticleProcessorServiceServer(s *grpc.Server, srv ArticleProcessorServiceServer) {
	s.RegisterService(&_ArticleProcessorService_serviceDesc, srv)
}

func _ArticleProcessorService_ProcessText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleProcessorServiceServer).ProcessText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IrisAPIsGRPC.ArticleProcessorService/ProcessText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleProcessorServiceServer).ProcessText(ctx, req.(*ProcessTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleProcessorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IrisAPIsGRPC.ArticleProcessorService",
	HandlerType: (*ArticleProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessText",
			Handler:    _ArticleProcessorService_ProcessText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ArticleProcessorService.proto",
}
